.gitignore
components.json
package.json
pnpm-lock.yaml
src/app/globals.css
src/app/login/page.tsx
src/app/page.tsx
src/lib/utils.ts
src/pages/login/ui/login-page.tsx
src/shared/ui/button.tsx

Feat: 로그인 화면 추가
1. 샤드시엔 버튼 추가
2. 로그인 화면 추가
>

Feat: 로그인 화면 추가

---

src/app/(auth)/payment/layout.tsx
src/app/(main)/chat/layout.tsx
src/app/(main)/search/layout.tsx
src/app/(main)/search/page.tsx
src/entities/search/model/type.ts
src/entities/search/ui/item-box.tsx
src/features/filter-search-result/ui/filter-category-dialog.tsx
src/features/filter-search-result/ui/sidebar.tsx
src/pages/search/ui/search-page.tsx
src/shared/model/type.ts
src/shared/ui/button.tsx
src/shared/ui/dialog.tsx
src/shared/ui/dropdown.tsx
src/shared/ui/footer.tsx
src/shared/ui/header.tsx
src/widgets/search/grid-items-widget.tsx

Feat: 서비스 탐색 페이지 UI 제작

---

src/app/(main)/my/layout.tsx
src/features/vendorMy/ui/edit-vendor-info.tsx
src/shared/ui/footer.tsx
src/shared/ui/header.tsx
src/shared/ui/signup-form.tsx
src/shared/ui/submit-custom-button.tsx
src/shared/ui/userheader.tsx
src/shared/ui/vendorheader.tsx

Refactor: footer header 수정
1. footer header 수정
2. 색 수정
>

Refactor: footer header 수정

---

.eslintrc.json
next.config.ts
src/sentry-dev.tsx

closes #45 
런타임 오버헤드를 제거하여 개발 환경 성능 향상
1. withSentryConfig 조건부 적용으로 개발환경에서 Sentry 관련 빌드 프로세스 건너 뛰기.
2. 웹팩 alias 설정을 통해 Mock 파일로 리다이렉트.
> 개선 전 : dev 서버 실행시간 3.4s, 첫 화면 랜딩 시간 4.3s
> 개선 후 : dev 서버 실행시간 1.5s, 첫 화면 랜딩 시간 2.8s 
전체적으로 50%의 가까운 성능 개선
>

Fix: sentry dev환경 설정 수정

---

src/entities/home/ui/home-second-section.tsx
src/entities/login/ui/login-fourth-section.tsx
src/entities/login/ui/login-third-bottom-section.tsx
src/entities/signup/ui/signup-popup.tsx
src/features/login/ui/login-control.tsx
src/features/login/ui/login-form.tsx
src/features/my/api/editInfoPost.ts
src/features/my/ui/edit-info.tsx
src/features/my/ui/review-modal.tsx
src/features/signup/api/signupVendorPost.ts
src/features/signup/ui/signup-user-form.tsx
src/features/signup/ui/signup-vendor-form.tsx
src/pages/my/ui/my-profile-page.tsx
src/shared/api/useFileUpload.tsx
src/shared/ui/button.tsx
src/shared/ui/signup-form.tsx
src/shared/ui/solu.tsx
src/shared/ui/submit-custom-button.tsx

Refactor: button 및 폼 로직 refactoring
1. button 공통 varient 추가
2. 폼 disabled 추가
3. file 업로드 공통 훅 추가
4. 폼 로직 세부프롭스 추가
>

Refactor: button 및 폼 로직 refactoring

---

fire-config.ts
package.json
pnpm-lock.yaml
src/features/chat/ui/chat-collection.tsx
src/features/chat/ui/chat-input.tsx
src/features/chat/ui/chat-test.tsx
src/pages/chat/ui/chat-page.tsx
src/widgets/chat/ui/chat-company-profile.tsx
src/widgets/chat/ui/chat-rooms.tsx
src/widgets/chat/ui/chatting.tsx

Feat: testChatting 구현 추후 수정 필요
1. testChatting 구현
2. 폴더 구조 수정
>

Feat: testChatting 구현 추후 수정 필요

---

src/app/api/auth/[...nextauth]/route.ts
src/app/types/next-auth.d.ts
src/entities/signup/ui/signup-layout.tsx
src/features/login/model/loginType.ts
src/features/login/ui/login-form.tsx
src/features/reset/api/resetPost.tsx
src/features/reset/ui/reset-form.tsx
src/features/signup/model/useSendEmail.tsx
src/features/signup/model/useVerifyEmail.tsx
src/features/signup/ui/signup-user-form.tsx
src/features/signup/ui/signup-vendor-form.tsx
src/shared/api/index-api.ts
src/shared/model/apiType.ts

Feat: email 관련 api연동 및 로그인 api 연결
1. 이메일 전송 api 연결
2. 이메일 인증 api 연결
3. 로그인 api 연결
>

Feat: email 관련 api연동 및 로그인 api 연결

---

src/features/signup/api/signupUser.ts
src/features/signup/api/signupUserPost.ts
src/features/signup/api/signupVendor.ts
src/features/signup/api/signupVendorPost.ts
src/features/signup/model/useVerifyEmail.tsx
src/features/signup/ui/signup-vendor-form.tsx
src/shared/api/index-api.ts

Feat: 회원가입 api 연동
1.벤더 회원가입 연동
2.고객 회원가입 연동
>

Feat: 회원가입 api 연동

---

next.config.ts
src/app/(main)/products/[id]/page.tsx
src/app/(vendor)/vendor/register/page.tsx
src/app/api/auth/[...nextauth]/route.ts
src/entities/vendorRegister/model/vendor-normal-info-category.ts
src/features/vendorRegister/ui/vendor-drop-input.tsx
src/pages/products/api/getSolution.ts
src/pages/products/model/type.ts
src/pages/products/ui/products-detail-page.tsx
src/pages/vendorRegister/api/register-solution.tsx
src/pages/vendorRegister/model/vendor-register-schema.ts
src/pages/vendorRegister/ui/vendor-register-page.tsx
src/pages/vendorRegister/ui/vendor-submit-modal.tsx
src/pages/vendorRegister/utils/vendor-category-mapping.ts
src/shared/api/index-api.ts
src/shared/api/server-api.ts
src/shared/ui/error-message.tsx
src/shared/ui/input.tsx
src/shared/ui/vendor-select.tsx
src/widgets/products/ui/product-detail.tsx
src/widgets/vendorRegister/ui/vendor-detail-info.tsx
src/widgets/vendorRegister/ui/vendor-keyword.tsx
src/widgets/vendorRegister/ui/vendor-normal-info.tsx
src/widgets/vendorRegister/ui/vendor-sale-info.tsx

closes #71 
- vendor 솔루션 등록
- vendor 솔루션 조회
- _추후 pdf 관련 기능 구현 필요_
>

feat: vendor 솔루션 등록, 솔루션 조회

---

src/entities/search/model/type.ts
src/entities/search/ui/item-box.tsx
src/views/products/ui/products-detail-page.tsx
src/widgets/products/ui/product-detail.tsx
src/widgets/search/grid-items-widget.tsx

closes #94 
- 이미지 url 연동
- 이미지 화질 개선
>

feat: 솔루션, 벤더 관련 이미지 연동

---

src/app/layout.tsx
src/shared/model/ChatMetaProvider.tsx
src/shared/model/useGetChatRooms.tsx
src/shared/model/useMessageSend.tsx
src/views/vendor/chat/ui/vendor-chat-page.tsx
src/widgets/vendor/chat/ui/vendor-chatting.tsx

Feat: vendorChat notFound 수정 추가
>

Feat: vendorChat notFound 수정 추가

---

src/app/(vendor)/vendor/layout.tsx
src/entities/chat/ui/chats-user.tsx
src/entities/chat/ui/chats-vendor.tsx
src/features/vendorChat/model/requestCategory.tsx
src/shared/api/create-room.ts
src/shared/api/get-room-information-by-id.ts
src/shared/model/roomType.ts
src/shared/model/useGetChatRooms.tsx
src/shared/model/useMessageSend.tsx
src/shared/ui/profile-side.tsx
src/widgets/user/chat/ui/chat-rooms.tsx
src/widgets/user/chat/ui/chatting.tsx
src/widgets/vendor/chat/ui/vendor-chatting.tsx
src/widgets/vendor/chat/ui/vendor-control.tsx

Fix: vendor chatting url 수정
1. vendor chatting url 수정
2. 채팅 스크롤 수정
>

Fix: vendor chatting url 수정

---

next.config.ts
src/app/(main)/search/api/getSolutionList.ts
src/app/(main)/search/page.tsx
src/shared/model/type.ts
src/views/products/model/type.ts
src/views/search/ui/search-page.tsx
src/views/vendorMy/api/urlToFile.ts
src/views/vendorMy/ui/vendor-my-profile-page.tsx
src/views/vendorRegister/api/register-solution.tsx
src/widgets/products/api/downloadFile.ts
src/widgets/products/ui/product-detail.tsx
src/widgets/vendorMy/ui/vendor-upload-banner.tsx

closes #103 
- vendor 마이페이지에서 배너 이미지 등록 버그 수정
- 솔루션 상세페이지에서 pdf 다운받을 수 있는 기능 구현
- 솔루션 리스트 페이지에서 정렬 토글 ui 수정 및 로직 작성
>

fix: vendor 업데이트 로직 수정, ui 버그 수정

---

route.ts
src/entities/chat/api/getFileRequest.ts
src/entities/chat/model/type.ts
src/entities/chat/model/useFileClick.tsx
src/entities/chat/ui/chat-user-bubble.tsx
src/entities/chat/ui/chat-user-request-card.tsx
src/entities/chat/ui/chat-vendor-bubble.tsx
src/entities/chat/ui/chats-user.tsx
src/entities/chat/ui/chats-vendor.tsx
src/features/my/api/editInfo.ts
src/features/my/api/editInfoPost.ts
src/features/my/ui/detail-control.tsx
src/features/my/ui/edit-info.tsx
src/shared/api/chat-file-post.ts
src/shared/api/get-messages-by-id.ts
src/shared/model/type.ts
src/shared/model/useMessageSend.tsx
src/shared/ui/chat-main-date.tsx
src/shared/ui/chatting-input.tsx
src/shared/ui/dropdown.tsx
src/shared/ui/userheader.tsx
src/views/my/ui/my-detail-page.tsx
src/widgets/my/api/getDashboard.ts
src/widgets/my/model/type.ts
src/widgets/my/ui/item-detail-section.tsx
src/widgets/user/chat/ui/chatting.tsx
src/widgets/vendor/chat/ui/vendor-chatting.tsx

feat: 파일 업로드 구현
1. 채팅 파일 업로드 구현
2. 채팅 관련 버그 수정
3. 채팅 로직 리팩토링
>

feat: 파일 업로드 구현

---

src/app/(main)/my/layout.tsx
src/entities/chat/ui/chat-user-request-card.tsx
src/entities/my/ui/detail-item.tsx
src/features/my/api/editInfo.ts
src/features/my/api/editInfoPost.ts
src/features/my/ui/edit-info.tsx
src/features/my/ui/review-modal.tsx
src/shared/lib/date-formatter.ts
src/shared/model/useGetChatRooms.tsx
src/shared/model/useMessageSend.tsx
src/widgets/my/ui/item-detail-section.tsx

feat: myPage관련 api 연동
1. 결제내역 api 연동 완료
2. 리뷰 연동 완료
3. mypage 정보수정 api 연동 완료
>

feat: myPage관련 api 연동

---

src/features/my/ui/review-modal.tsx
src/shared/lib/date-formatter.ts
src/views/products/ui/products-detail-page.tsx
src/widgets/products/api/getReviewList.ts
src/widgets/products/model/type.ts
src/widgets/products/ui/product-chart.tsx

feat: reviewList api 연동
feat: reviewList api 연동
>

Feat: reviewList api 연동

---

src/shared/api/create-room.ts
src/shared/api/send-message-json.ts
src/shared/model/ChatMetaProvider.tsx
src/shared/model/roomType.ts
src/shared/model/useMessageSend.tsx
src/views/products/ui/products-detail-page.tsx
src/widgets/products/ui/inquire-card.tsx

feat: chatRoom solutionName 추가
1. solutionName 방에 추가
>

 feat: chatRoom solutionName 추가

---

src/app/(vendor)/vendor/calculate/page.tsx
src/entities/vendorHome/ui/vendor-line-chart.tsx
src/shared/api/create-room.ts
src/shared/api/send-message-json.ts
src/shared/model/ChatMetaProvider.tsx
src/shared/model/roomType.ts
src/shared/model/useMessageSend.tsx
src/views/vendorCalculate/ui/vendor-calculate-page.tsx
src/views/vendorHome/ui/verndor-home-page.tsx
src/widgets/products/ui/inquire-card.tsx
src/widgets/vendorCalculate/ui/vendor-calculate-board.tsx
src/widgets/vendorHome/api/getBoardCount.ts
src/widgets/vendorHome/ui/vendor-board.tsx
src/widgets/vendorHome/ui/vendor-chat-widget.tsx
src/widgets/vendorHome/ui/vendor-marketing-statistics copy.tsx
src/widgets/vendorHome/ui/vendor-notice-widget.tsx

closes #114 
- 벤더 홈 실시간 상담 채팅 현황 ui
- 상담 대기 현황 임시 ui
>

feat: vendor 페이지 실시간 상담 관련 내역, 카운트 추가

---

src/auth.ts
src/shared/api/index-api.ts
src/shared/lib/error-handler.ts

fix: 로그아웃 버그 수정 및 에러 표시 수정
1. 24시간 지나면 로그아웃되게 설정
2. 클라이언트 화면 에러 토스트 메세지 수정
>

fix: 로그아웃 버그 수정 및 에러 표시 수정

---

src/views/payment/model/type.ts
src/views/products/ui/products-detail-page.tsx
src/widgets/payment/ui/order-details-widget.tsx
src/widgets/payment/ui/total-price-widget.tsx
src/widgets/products/api/createPaymentEvent.ts
src/widgets/products/model/type.ts
src/widgets/products/ui/inquire-card.tsx

feat: 바로 구매하기 로직 추가 

---

src/views/vendorMy/api/updateVendorInfo.ts
src/views/vendorMy/model/vendor-update-schema.ts
src/views/vendorMy/ui/vendor-my-profile-page.tsx
src/widgets/vendorMy/ui/vendor-customer-overview.tsx
src/widgets/vendorMy/ui/vendor-upload-logo.tsx

feat: vendor 정보 수정

---

src/app/(main)/search/page.tsx
src/app/globals.css
src/entities/chat/ui/chat-user-payComplete-card.tsx
src/entities/chat/ui/chat-user-request-card.tsx
src/entities/chat/ui/chat-vendor-request-card.tsx
src/entities/home/ui/home-first-section.tsx
src/entities/home/ui/home-second-section.tsx
src/features/home/ui/main-category-buttons.tsx
src/features/my/ui/edit-info.tsx
src/features/signup/ui/signup-industry-form.tsx
src/features/signup/ui/signup-vendor-form.tsx
src/features/vendorChat/model/requestCategory.tsx
src/features/vendorChat/ui/request-pay-form.tsx
src/shared/api/index-api.ts
src/shared/model/categoryMap.ts
src/shared/model/industryMap.ts
src/shared/ui/chat-main-date.tsx
src/shared/ui/profile-side.tsx
src/views/home/ui/home-page.tsx
src/widgets/user/chat/ui/chat-company-profile.tsx
src/widgets/vendor/chat/ui/vendor-control.tsx

Fix: 각종 ui 관련 부분 수정
1. 윤주씨가 언급한 css 관련 자잘한 부분 다 수정
2. 카테고리 부분 shared로 빼고 전체적으로 수정
3. 결제 요청 가능하게 수정
4. 채팅 마지막 날 표시되게 설정
5. 마이페이지 ui css 수정
>

Fix: 각종 ui 관련 부분 수정

---

next.config.ts
src/app/(main)/search/api/getSolutionList.ts
src/app/(main)/search/page.tsx
src/entities/vendorRegister/model/vendor-normal-info-category.ts
src/features/filter-search-result/ui/sidebar.tsx
src/features/home/model/home-button-category.ts

fix: 솔루션 카테고리 필터링 오류 수정

---

src/app/(main)/my/layout.tsx
src/app/(vendor)/vendor/layout.tsx
src/entities/my/ui/vendor-profile-side.tsx
src/shared/ui/profile-side.tsx

fix: vendor 사이드바 입점 관련 ui 수정

---

src/app/(vendor)/vendor/layout.tsx
src/auth.ts

[no-issue] fix: header 이름 변경

---

src/features/signup/model/useSendEmail.tsx
src/features/signup/ui/signup-user-form.tsx
src/features/signup/ui/signup-vendor-form.tsx
src/shared/api/index-api.ts
src/shared/api/server-api.ts
src/shared/lib/error-handler.ts
src/shared/model/backend-error-map.ts
src/shared/ui/profile-side.tsx

fix: 에러메세지 & 각종 ui 수정

---

src/shared/api/server-api.ts
src/views/vendorUpdate/api/updateSolution.ts
src/views/vendorUpdate/ui/vendor-update-page.tsx

closes #160 
- 솔루션 수정 api 변경 대응 로직 수정
>

fix: 솔루션 수정 api 변경 대응 로직 수정

---

src/entities/product/ui/pie-chart.tsx
src/views/products/ui/products-detail-page.tsx
src/views/vendorMy/model/type.ts
src/views/vendorMy/ui/vendor-my-profile-page.tsx
src/widgets/products/ui/product-chart.tsx
src/widgets/vendorMy/ui/vendor-customer-overview.tsx

closes #162 
- 솔루션 상세 페이지 pie-chart 실제 데이터로 변경
>

feat: 솔루션 통계 그래프 api 연동

---

src/app/(auth)/payment/page.tsx
src/app/(auth)/payment/success/page.tsx
src/entities/chat/ui/chat-vendor-cancel-request-card.tsx
src/entities/chat/ui/chat-vendor-payComplete-card.tsx
src/shared/api/request-post.ts
src/shared/api/send-message-json.ts
src/views/payment/model/type.ts
src/views/payment/ui/payment-page.tsx
src/views/payment/ui/payment-success-page.tsx
src/widgets/payment/ui/payment-method-widgets.tsx
src/widgets/products/ui/inquire-card.tsx

fix: 바로 결제시 채팅창 api 요청 오류
